name: sonamobi
description: Mobile interface to Sonaveeb
publish_to: 'none'
version: 1.1.0+8

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  google_fonts: ^6.2.1
  gtranslate_v2: ^1.0.2
  html: ^0.15.1
  http: ^1.2.2
  intl: ^0.20.0
  logging: ^1.2.0
  shared_preferences: ^2.0.15
  sqflite: ^2.4.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/neurotolge.png
    - assets/gtranslate.png
    - assets/sonaveeb.png

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#4125d0"
  adaptive_icon_foreground: "icon/sonamobi-icon.png"
  ios: true
  remove_alpha_ios: true
  image_path: "icon/sonamobi-icon.png"
