name: sonamobi
description: Mobile interface to Sonaveeb
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  html: ^0.15.1
  http: ^1.2.2
  intl: ^0.19.0
  logging: ^1.2.0
  shared_preferences: ^2.0.15
  sqflite: ^2.4.0
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
